---
deployment:
  tasks:
    - export DEPLOYPATH=/home/capone/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -r img $DEPLOYPATH
    - /bin/cp -r pages $DEPLOYPATH